matrix:
  allow_failures:
    - os:
      - osx
      - windows
  include:
    - os: osx
      osx_image: xcode9.4
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: linux
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: windows
      language: sh
      before_script: choco install jdk8
      script: gradlew.bat clean test -Dbrowser=firefox-headless

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
