matrix:
  allow_failures:
    - os: windows
    - os: osx
  include:
    - os: osx
      before_install: bash .travis/prepare-osx.sh
      script: ./gradlew clean test -Dbrowser=safari
    - os: linux
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: windows
      language: shell
      before_install: bash .travis/prepare-win.sh
      script: ./gradlew clean test -Dbrowser=ie

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
