matrix:
  allow_failures:
    - os: windows
    - os: osx
  include:
    - os: osx
      osx_image: xcode9.4
      script: ./gradlew clean test -Dbrowser=safari
    - os: linux
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: windows
      language: sh
      before_script: choco install jdk8
      script: ./gradlew clean test -Dbrowser=ie

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
