matrix:
  allow_failures:
    - os: windows
#    - os: osx
  include:
    - os: osx
      before_install:
        - curl -s http://get.sdkman.io | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 8.0.202-zulu
        - sudo safaridriver --enable
        - osascript -e 'quit app "Safari"'
      script: ./gradlew clean test -Dbrowser=safari -Pserial
    - os: linux
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: linux
      language: java
      jdk: openjdk8
      addons:
        chrome: stable
      script: ./gradlew clean test -Dbrowser=chrome-headless
    - os: linux
      language: java
      jdk: openjdk8
      before_install:
        - sudo snap install opera
      script: ./gradlew clean test -Dbrowser=opera

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
