matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: linux
      language: java
      jdk: openjdk8
      script: ./gradlew clean test -Dbrowser=firefox-headless
    - os: windows
      before_script: choco install jdk8
      script: gradlew.bat clean test -Dbrowser=firefox-headless
