version: '{build}'

skip_tags: true

clone_depth: 5

install:
  - choco install jdk8
  - choco install ie11
  - choco install firefox
  - choco install googlechrome
  - choco install opera
  - refreshenv

build_script:
  - gradlew.bat clean test -Dbrowser=ie

